"""Give every visible model a database row and a wildcard read grant.

Prerequisite for turning model access control on. get_filtered_models treats a
model with no row as admin-only, and only 7 of 130 have one, so flipping the
bypass first would leave every non-admin with 7 models and nothing logged.

The row copies the capabilities the API reports for that model. An empty meta
would strip vision, tools and web search from models that have them, which is a
behaviour change smuggled in behind a visibility fix.

Idempotent, and safe to re-run ONLY because it now grants exclusively to the
base models it discovered. That scope is load-bearing rather than tidiness. A
user's agent is a model row too, and what makes an agent private is the ABSENCE
of a wildcard grant, so a grant statement written as "every row that lacks one"
would publish every private agent on this platform, instructions included, the
next time anyone ran it to fix a missing model. Derived models are skipped
below and the grant is scoped to an explicit id list.

Run inside the mcp-proxy container (PyJWT).
"""
import json
import os
import sys
import urllib.error
import urllib.request

BASE = os.environ.get("PROBE_BASE", "https://ai-ui.coolestdomain.win")
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0 Safari/537.36")


def admin_models(token):
    req = urllib.request.Request(BASE + "/api/models", headers={
        "Authorization": "Bearer " + token, "User-Agent": UA})
    with urllib.request.urlopen(req, timeout=40) as r:
        body = json.load(r)
    if isinstance(body, list):
        return body
    else:
        return body.get("data", [])


def main():
    token = os.environ["ADMIN_TOKEN"]
    rows = []
    try:
        for m in admin_models(token):
            mid = m.get("id")
            if not mid:
                continue
            # Skip derived models. An admin sees every row, which now includes
            # other people's agents, and an agent is exactly a model with a
            # base_model_id. Granting one of those would hand somebody's
            # private assistant to all nine users.
            if (m.get("info") or {}).get("base_model_id"):
                continue
            if mid.startswith("agent-"):
                continue
            rows.append({
                "id": mid,
                "name": m.get("name") or mid,
                "capabilities": (m.get("info") or {}).get("meta", {}).get("capabilities"),
            })
    except urllib.error.HTTPError as e:
        print("HTTP error from admin models: %s" % e.code, file=sys.stderr)
        return 1
    except urllib.error.URLError as e:
        print("Connection error from admin models: %s" % e.reason, file=sys.stderr)
        return 1
    # Emit SQL rather than JSON. The earlier draft wrote JSON and left a psql
    # variable for a later step to interpolate, which no step ever set.
    def q(v):
        return "'" + str(v).replace("'", "''") + "'"

    out = ["-- generated by backfill_model_grants.py; safe to re-run.",
           "-- Grants below are scoped to discovered BASE models only,"
           " never to every row lacking a grant: that would publish"
           " every private agent."]
    for r in rows:
        meta = json.dumps({"capabilities": r["capabilities"]}
                          if r["capabilities"] else {})
        out.append(
            "INSERT INTO model (id, user_id, base_model_id, name, meta, params,"
            " is_active, created_at, updated_at) SELECT " + q(r["id"]) +
            ", (SELECT id FROM \"user\" WHERE role='admin' ORDER BY created_at"
            " LIMIT 1), NULL, " + q(r["name"]) + ", " + q(meta) + "::json,"
            " '{}'::json, true, extract(epoch from now())::bigint,"
            " extract(epoch from now())::bigint WHERE NOT EXISTS (SELECT 1 FROM"
            " model m WHERE m.id = " + q(r["id"]) + ");")
    out.append(
        "-- Arena models are filtered by a different branch of"
        " get_filtered_models, which reads grants from the model's OWN"
        " meta.access_grants JSON and then returns, so it never consults the"
        " access_grant table. Granting only in the table left every non-admin"
        " without the arena model. This is the public-read shape documented in"
        " utils/access_control has_access.")
    out.append(
        "UPDATE model SET meta = jsonb_set(coalesce(meta::jsonb, '{}'::jsonb),"
        " '{access_grants}', '[{\"principal_type\": \"user\","
        " \"principal_id\": \"*\", \"permission\": \"read\"}]'::jsonb,"
        " true)::json WHERE id = 'arena-model' AND (meta::jsonb -> 'access_grants')"
        " IS NULL;")
    # Scoped to the ids above, never "every row without a grant". See the
    # module docstring: that broader form would publish every private agent.
    out.append(
        "-- Grants are deliberately limited to the base models listed above."
        " Do NOT relax this to every row lacking a grant: an agent is a model"
        " row whose privacy IS the absence of a grant.")
    if rows:
        ids = ", ".join(q(r["id"]) for r in rows)
        out.append(
            "INSERT INTO access_grant (id, resource_type, resource_id,"
            " principal_type, principal_id, permission, created_at)"
            " SELECT gen_random_uuid()::text, 'model', m.id, 'user', '*',"
            " 'read', extract(epoch from now())::bigint FROM model m"
            " WHERE m.id IN (" + ids + ") AND NOT EXISTS ("
            "SELECT 1 FROM access_grant g WHERE g.resource_type='model'"
            " AND g.resource_id=m.id AND g.principal_type='user'"
            " AND g.principal_id='*' AND g.permission='read');")

    path = os.environ.get("BACKFILL_OUT", "/tmp/apply_model_rows.sql")
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print("described %d models -> %s" % (len(rows), path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
